#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

# Clean time directories only
rm -rf *[1-9]*
rm -f log.*
rm -r postProcessing/

# -----------------------------------------------------------------------------
